### PR TITLE
Replace settings strings by ids

### PR DESCRIPTION
**Pull request by codeschrat**
This is a follow-up to #377: Replace all magic strings used for settings keys by enum values.

As I don't see how to verify the correct replacement with unit tests, I compiled small commits with text substitutions only and formatted the code afterwards; this should make the review easier.

I'm looking forward any comments.

### CODE REVIEW

**Comment by exactly-one-kas** [comment]
This look very good!

I'll look into why the treeview test fails, after that we should merge it without problems

**Review by exactly-one-kas — CHANGES_REQUESTED** [review]
The only thing blocking this is the failing test, I'll look into it

**Comment by codeschrat** [comment]
> The only thing blocking this is the failing test, I'll look into it

I made a rebase, all tests are green now.

**Review by Murmele — APPROVED** [review]

**Comment by Murmele** [comment]
Looks really good. Thank you!

**Pull request merged**
