### PR TITLE
Restore the default FileContextMenu in DoubleTreeWidget

### PR DESCRIPTION
**Pull request by stefanknotzer**
Use the apps full blown `FileContextMenu` in `DoubleTreeWidget`.

Might also address issue #90

### CODE REVIEW

**Comment by Martin2278** [comment]
Sorry for not doing anything yet. I hope I get the time this week

**Comment by Murmele** [comment]
Amazing thanks!

**Comment by Murmele** [comment]
When staging, the treeview is not updated and the file stays in the unstaged treeview

**Comment by stefanknotzer** [comment]
There must be hiding a bug somewhere :worried:, I will have a look on that

**Comment by Murmele** [comment]
I checked too shortly but I did not find. When doing refresh, everything is fine ^^

**Comment by stefanknotzer** [comment]
I forgot about the weird signalling concerning index changes. This means I would need to add ugly workarounds to `FileContextMenu`. So for now this feature is not possible - the `DoubleTreeWidget` and `DiffView` need a basic rework prior to bring the `FileContextMenu` back.

**Comment by Martin2278** [comment]
@stefanknotzer I think you can let it open and marking it as draft. Sorry not being able to support at the moment ...

**Pull request closed without merging**
