### PR TITLE
Add Mac OS Homebrew installation method

### PR DESCRIPTION
**Pull request by HNKNTA**
Cask file:
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/gittyup.rb

### CODE REVIEW

**Comment by Murmele** [comment]
You can also add the information to the github page (just add the info to the docs/index.md file):

https://github.com/Murmele/Gittyup/blob/master/docs/index.md

**Comment by HNKNTA** [comment]
> You can also add the information to the github page (just add the info to the docs/index.md file):
> 
> https://github.com/Murmele/Gittyup/blob/master/docs/index.md

Added, with link to the README part

**Comment by Murmele** [comment]
Instead of the link to the repo use the brew url: https://formulae.brew.sh/cask/gittyup
What do you think?

**Comment by Murmele** [comment]
[Homebrew](https://formulae.brew.sh/cask/gittyup) Something like this?

Created with https://michaelcurrin.github.io/badge-generator/#/generic

**Comment by HNKNTA** [comment]
> 

Not sure if I got what you've mentioned in a correct way, but I've added an icon. Looks more fresh, but the geometry kinda moved a little.

**Comment by Murmele** [comment]
@HNKNTA what do you think about now?

@exactly-one-kas what do you think about?

I added the link to the stable also for macOS if someone wants to download directly the dmg file

**Comment by HNKNTA** [comment]
> @HNKNTA what do you think about now?
> 
> @exactly-one-kas what do you think about?
> 
> I added the link to the stable also for macOS if someone wants to download directly the dmg file

Looks fine for me, it makes sense to have choice of direct installation together with the Homebrew one.

**Comment by Murmele** [comment]
ok perfect. Than @exactly-one-kas can merge it if it is ok for him

**Review by exactly-one-kas — APPROVED** [review]

**Comment by exactly-one-kas** [comment]
@Murmele If we're going to officially endorse Homebrew, should we try to put the cask directly into this repo?
@HNKNTA Or would that break existing installations?

**Comment by Murmele** [comment]
I thought about something similar. It might be also a security issue giving away the maintenance here. Where are the casks stored? Do we have access to the cask?

**Comment by HNKNTA** [comment]
@exactly-one-kas, @Murmele 

All the casks files (ruby files, consider it as installation recipes) are laying in the main git repo: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/gittyup.rb

The required changes can be done via PR to that repo. For instance, a new version bump can be done with a simple command that does the work for you `brew bump-cask-pr`.

If you'd like to maintain the cask file by yourself, it's possible via [Homebrew Tap](https://docs.brew.sh/Taps) - it's like a third-party repo for brew. I think it won't affect the existing installations, according to the [documentation](https://docs.brew.sh/Taps#formula-with-duplicate-names), but you will have to use the full package name, something like `brew install murmele/mittyup/gittyup`.  

And the final decision will be up to a user, which installation way to use. 

But my opinion is 99.9% of tools are laying down in the main repo, and I would rather be very suspicious of those who insist on using their own tap with no good reason for it.

**Comment by exactly-one-kas** [comment]
Yeah, that makes sense
My use case was automatic publishing, but I guess that's not possible without automatically creating PRs (which the maintainers probably wouldn't like too much? I haven't found information on that yet)

Making or own repo would probably make most sense for pre-release builds

**Comment by Murmele** [comment]
> Yeah, that makes sense My use case was automatic publishing, but I guess that's not possible without automatically creating PRs (which the maintainers probably wouldn't like too much? I haven't found information on that yet)
> 
> Making or own repo would probably make most sense for pre-release builds

Sorry I don't understand which files are stored in the second repo then?😅

**Comment by exactly-one-kas** [comment]
I meant "putting the cask into our own repo", sorry

**Comment by Murmele** [comment]
> 

I like the approach we have for flatpak. The flatpak manifest is only at one place. But those guys I trust haha ^^ But to get it to homebrew we always need to make a pullrequest. So there must be someone which updates the cask there. It is the same for the flatpak. I have to update the version there too manually.

**Comment by HNKNTA** [comment]
I think the PR creation action on the release could be automated, I don't have experience with GitHub actions, but after short searching there are plugins supporting brew version bump, and in theory it's just a one-line command.

If you have active testers/beta users on Mac, who prefer Homebrew, a tap (own repo) could be created, as @exactly-one-kas mentioned.

**Comment by Murmele** [comment]
> 

Yes this is a good idea. I did not understand that earlier sorry about. How difficult is it to setup our own repo?

**Comment by HNKNTA** [comment]
It's rather easy, described in [docs](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap). By default, it uses the separate repo for the tap, starting with "homebrew-", and containing Formula or Cask dir with ruby files inside, plus some GitHub actions files (don't know what's the purpose of it)

But it's also possible to use the same git repo with source files, according to [this](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap#creating-a-tap) and [this](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap#installing) paragraphs.

**Pull request merged**
