### PR TITLE
Add option to always show window maximized

### PR DESCRIPTION
**Pull request by monks-dev**
Solved this  #676

This is off by default when launching gittyup for the first time.

### CODE REVIEW

**Comment by monks-dev** [comment]
First time ever committing to a open source project.

**Comment by Murmele** [comment]
@monks-dev can you fix the formatting? In the repository there is a script called `cl-fmt.sh`

**Comment by monks-dev** [comment]
> @monks-dev can you fix the formatting? In the repository there is a script called `cl-fmt.sh`
> 
> I created an issue I have to checkout the linux build problem: #722

# Just ran clang format

image

**Comment by Murmele** [comment]
@monks-dev can you rebase? Hopefully it fixes the build issue

**Comment by Murmele** [comment]
There is a ci issue, I have to fix first before I can merge this. Sorry for the inconvenience

**Pull request merged**
