### PR TITLE
Restore openssl dependency

### PR DESCRIPTION
**Pull request by stefanknotzer**
Windows: the included openssl library is very convenient - no need to install 3rd party openssl builds
Linux: openssl is very likely already installed - dependency could be removed for Linux builds
MAC: I have no idea, someone needs to verify

pack: configuration and plugins for CPack fixed. "make package" / "ninja package" work for Linux / Windows

(sorry for the huge pack/CMakeLists.txt diff due to code reformatting. please don't use tabs!)

### CODE REVIEW

**Comment by Murmele** [comment]
I think the idea of adding the dependencies was previously that the compilation is always working and you don't have to fix any problems with upcomming versions of external dependencies. But I agree with you that some dependencies should be up to date

**Comment by stefanknotzer** [comment]
This PR would actually address issue #78 
With the openssl dependency I can build a Windows installer binary without external dependency.

Please let me know if the openssl submodule/dependency is to be removed soon.
Remark: I do not need the dependency on linux - this PR could be changed accordingly.

**Comment by exactly-one-kas** [comment]
> This PR would actually address issue #78 With the openssl dependency I can build a Windows installer binary without external dependency.

This could actually solve a (potential) problem with my solution to the issue: #80 - It currently works fine on my machine using the installer, but I also have OpenSSL installed globally. I'll check tomorrow if it still works without that 🙈

> (sorry for the huge pack/CMakeLists.txt diff due to code reformatting. please don't use tabs!)

I've been working on that as well using CI checks: https://github.com/exactly-one-kas/Gittyup/commits/style-checks
@Murmele I'd like to propose enforcing code style using cmake-format and clang-format

**Comment by stefanknotzer** [comment]
Removing the openssl submodule/dependency reduces maintenance - that is a big plus!
I would provide a shell script/command file instead to re-install/download/build openssl into Gittyup - especially for the Windows developer.

> Please let me know if the openssl submodule/dependency is to be removed soon.

**Comment by Murmele** [comment]
> > This PR would actually address issue #78 With the openssl dependency I can build a Windows installer binary without external dependency.
> 
> This could actually solve a (potential) problem with my solution to the issue: #80 - It currently works fine on my machine using the installer, but I also have OpenSSL installed globally. I'll check tomorrow if it still works without that 🙈
> 
> > (sorry for the huge pack/CMakeLists.txt diff due to code reformatting. please don't use tabs!)
> 
> I've been working on that as well using CI checks: https://github.com/exactly-one-kas/Gittyup/commits/style-checks @Murmele I'd like to propose enforcing code style using cmake-format and clang-format

Good idea, is theee a github action to aplly and checks if the codestyle is fine, so we don't get any dirty code style in it? Also there should be a small script in the repo to apply it before pushing.

**Comment by Murmele** [comment]
@exactly-one-kas @stefanknotzer at the moment I am quite busy with another project, so I don't have that much time yet, but you are doing a really good job and so you can also decide which way we would like to go! But I'm trying to stay on track and  be responsible. Hopefully I get more time soon.

**Comment by Murmele** [comment]
looks fine for me

**Review by Murmele — APPROVED** [review]

**Comment by Murmele** [comment]
@stefanknotzer can you test again? I had to solve merge conflicts

**Comment by stefanknotzer** [comment]
Works!

**Pull request merged**
