### PR TITLE
Fix load selection

### PR DESCRIPTION
**Pull request by Murmele**
image1

### CODE REVIEW

**Comment by Murmele** [comment]
[Uploading TreeViewCollapseCount.zip…]()

Steps to reproduce:
1) Open attached repository in Gittyup
2) Stage folder/subfolder/file.txt
3) Expand all staged files
4) Select folder/subfolder/file.txt in staged TreeView
5) Commit

Gittyup v1.1.1 - Samstag, 24. September 2022 - 332164d

**Review by exactly-one-kas — CHANGES_REQUESTED** [review]
grafik
It's still happening for me with d4cd8c9

**Comment by Murmele** [comment]
> grafik It's still happening for me with [d4cd8c9](https://github.com/Murmele/Gittyup/commit/d4cd8c9ebfec854419f17a17171f42f2d77a66c2)

Is this the unittest?
image
Do you see those changes?

**Comment by Murmele** [comment]
Now it should be fine

**Review by exactly-one-kas — APPROVED** [review]

**Comment by exactly-one-kas** [comment]
Yep, works without issue now

**Pull request merged**
