### PR TITLE
Fix typo in documentation: Starring not Staring.

### PR DESCRIPTION
**Pull request by jpwhiting**
We aren't staring at our commits, we are adding stars.

### CODE REVIEW

**Review by mwerle — APPROVED** [review]

**Comment by jpwhiting** [comment]
I don't understand github's new "At least 1 approving review is required by reviewers with write access." maybe you don't have write access? I don't see any merge button anywhere, feel free to merge. I can't unless I'm missing something somewhere.

**Comment by jpwhiting** [comment]
Ah, maybe you also don't have write access. Makes sense, ok.

**Comment by mwerle** [comment]
> Ah, maybe you also don't have write access. Makes sense, ok.

Indeed I don't.. don't really know how this repo is being run.. just figured doing a review would allow the owner(s) to merge this more quickly.

**Comment by Murmele** [comment]
I will merge it when the CI is going through. Thank you for the contribution!

**Review by Murmele — APPROVED** [review]

**Pull request merged**
