### PR TITLE
Adds support for keyboard-interactive SSH auth

### PR DESCRIPTION
**Pull request by exactly-one-kas**
Removes authentication stop when (only) SSH key auth failed

### CODE REVIEW

**Comment by Murmele** [comment]
There are some conflics

**Comment by Murmele** [comment]
I will test it out

**Comment by Murmele** [comment]
For some reason when I remove my ssh files, I still get no error. How can I test this?

**Comment by exactly-one-kas** [comment]
> For some reason when I remove my ssh files, I still get no error. How can I test this?

What do you mean by remove? If the SSH key is in a default location (eg `~/.ssh/id_rsa`) it will be picked even if the SSH agent doesn't have the key loaded.

I tested this by checking with 2FA via google-authenticator via PAM, as well as using keys that are and aren't registered with my SSH GIT account

**Comment by Murmele** [comment]
> 

I removed the ssh keys from .ssh and restarted the computer. Then I tried to fetch from a git repository where my key is stored. Then I get the error message:      Unable to fetch from 'origin' - error authenticating: 

Do you have a video how it looks like for you?

**Comment by exactly-one-kas** [comment]
I think you have the wrong idea: In order to use keyboard-interactive authentication, the SSH server has to offer it. This is usually disabled by default; GitHub, GitLab, BitBucket and the likes have it disabled too.

This PR solves the following circumstance I have on my personal server: I use 2FA using the google-authenticator PAM module which asks for a OTP via a keyboard-interactive prompt.

The module can be configured to be optional, however this still sends a keyboard-interactive authentication request with no prompts. (Which can be automatically answered, see [Remote.cpp:252-253](https://github.com/Murmele/Gittyup/blob/5eb756619fd9159de790023cfdc889fa38a6d0bc/src/git/Remote.cpp#L252-L253))

Since it's a system-wide configuration and somewhat hard to disable this specifically for the GIT user, I decided to simply improve Gittyup's SSH handling, since the standard GIT CLI handles this without any issue.

image
image

**Comment by Murmele** [comment]
Ah ok I understand. Thank you for the explanation!

**Pull request merged**
