### PR TITLE
do tests before publishing

### PR DESCRIPTION
**Pull request by Murmele**
do not publish if tests are not successfull

### CODE REVIEW

**Comment by Murmele** [comment]
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

**Comment by Murmele** [comment]
Installing all missing xcb libraries did not help
sudo apt update -q
          sudo apt install -y -q build-essential libgl1-mesa-dev
          sudo apt install -y -q libxcb-icccm4
          sudo apt install -y -q libxcb-image0
          sudo apt install -y -q libxcb-util1
          sudo apt install -y -q libxcb-keysyms1
          sudo apt install -y -q libxcb-randr0
          sudo apt install -y -q libxcb-render-util0
          sudo apt install -y -q libxcb-xinerama0

**Comment by exactly-one-kas** [comment]
I guess that the VM doesn't have any screens to output to. Maybe try using Xvfb?

**Comment by Murmele** [comment]
> I guess that the VM doesn't have any screens to output to. Maybe try using Xvfb?

Yes, I tried offscreen, minimal, but the did not work either

**Comment by Murmele** [comment]
> I got tests to run again, though not all of them successfully: https://github.com/exactly-one-kas/Gittyup/tree/FixTests [exactly-one-kas@cbe2f5d](https://github.com/exactly-one-kas/Gittyup/commit/cbe2f5ddb6b7f21a45647a026f893aff015a7bd5)

Which one do not run through, you can just push to this branch

**Comment by exactly-one-kas** [comment]
The following tests fail:

- init_repo: Timeout for FS change detection
- merge: Unknown CTest timeout
- branches_panel: Assertions failed for "watcher" and "upstream" while initializing the test
- index: Assertions failed for "dirty" in stageAddition()

**Comment by Murmele** [comment]
> The following tests fail:
> 
>     * init_repo: Timeout for FS change detection
> 
>     * merge: Unknown CTest timeout
> 
>     * branches_panel: Assertions failed for "watcher" and "upstream" while initializing the test
> 
>     * index: Assertions failed for "dirty" in stageAddition()

test_index:
- The problem is that RepoView::statusChanged() will never called. This signal will be emitted when ComitList::statusChanged() is emitted. But when staging or unstaging, why the commitlist should change?

**Comment by Murmele** [comment]
Here they are using a vnc server
https://www.froglogic.com/blog/tip-of-the-week/running-gui-tests-on-each-commit-in-gitlab/

**Comment by Murmele** [comment]
For me setting the environment variable QT_QPA_PLUGIN offscreen/ minimal it still shows me the gui. When setting it directly in the application, it does not show me the gui but the tests are working fine.

**Comment by Murmele** [comment]
@exactly-one-kas just revert my things if you find a way to fix it. Tried just a few things out

**Comment by Murmele** [comment]
> * branches_panel: Assertions failed for "watcher" and "upstream" while initializing the test

Maybe this is because the github CI is not able to access the internet?

**Comment by Murmele** [comment]
- init_repo: Timeout for FS change detection
For some reason the head is not valid

**Comment by Murmele** [comment]
@exactly-one-kas so anoying. The tests failed, because the username and the email failed.

- name: Set git name and email
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@yourdomain.com"
          git config --list

I have to clean up next days. But now the tests are running through

**Comment by Murmele** [comment]
Only one tests fails now. The Diff.
At the git tag TestsSuccessful all of them worked. Have to compare why it fails

**Pull request merged**
