### PR TITLE
Branding updates

### PR DESCRIPTION
**Pull request by exactly-one-kas**

### CODE REVIEW

**Comment by Murmele** [comment]
Why would you like to use a different font between [logo-type_light-textobj.svg](https://github.com/Murmele/Gittyup/pull/281/files#diff-5375cc527089424a30723556b7857f41b8c695e8d2f080ce207ade147d0cdaec) and  [rsrc/logo-type_light.svg](https://github.com/Murmele/Gittyup/pull/281/files#diff-6ef0a27e3e4622570e6403f811747b308660469a9de6d03a480ab8051d582703)?

Is this just for macos?

**Comment by exactly-one-kas** [comment]
It's still the same font, do you have Fira Code installed? This would be the exact issue I wanted to fix lol
grafik

**Comment by Murmele** [comment]
I never realized that we still have a GitAhead background in there ^^

image

We have to rethink for deleting files, because showing twice the same image might be confusing

**Review by Murmele — APPROVED** [review]

**Comment by Murmele** [comment]
The backgrounds look amazing. Especially the white one :D

**Comment by Murmele** [comment]
Can I merge this?

**Comment by exactly-one-kas** [comment]
> The backgrounds look amazing. Especially the white one :D

The white one? Do you mean `dmg-background.svg`? That should be the same as the PNG, but Browsers don't render it properly

**Comment by Murmele** [comment]
> > The backgrounds look amazing. Especially the white one :D
> 
> The white one? Do you mean `dmg-background.svg`? That should be the same as the PNG, but Browsers don't render it properly

Ah ok ^^

**Pull request merged**
