### PR TITLE
Delete timeline causes crash on windows #680

### PR DESCRIPTION
**Pull request by wolfseifert**

### CODE REVIEW

**Comment by Murmele** [comment]
Can you fix the formatting?

**Comment by wolfseifert** [comment]
I made the changes without reformatting, directly at github. I have no idea what is wrong with the formatting. Is the existing code compliant with this formatting check? Maybe you should disable the formatting check for PRs.

**Comment by Murmele** [comment]
> I made the changes without reformatting, directly at github. I have no idea what is wrong with the formatting. Is the existing code compliant with this formatting check? Maybe you should disable the formatting check for PRs.

you have to execute the cl-fmt.sh script. Maybe because the line got longer and then it should be wrapped or something like this.

**Comment by wolfseifert** [comment]
Done.

**Comment by Murmele** [comment]
Thanks :) i will merge when ci runs through

**Pull request merged**
