### PR TITLE
Adds file manager button 

### PR DESCRIPTION
**Pull request by exactly-one-kas**
Implements gitahead/gitahead#262

### CODE REVIEW

**Comment by Murmele** [comment]
image

**Comment by exactly-one-kas** [comment]
> image

huh?

**Comment by Murmele** [comment]
> > image
> 
> huh?

Better adding here the filesystem lineedit

**Comment by Murmele** [comment]
works fine. Event trying to spawn host filemanager with "flatpak-spawn --host dolphin" works perfect.
Can I merge?

**Comment by exactly-one-kas** [comment]
Go ahead - I've been using this feature for almost a year now

**Pull request merged**
