### PR TITLE
Load files and hunks depending on scrollbar position

### PR DESCRIPTION
**Pull request by stefanknotzer**
FileWidget:
When fetchMore() is called without parameter up to 4 more hunks are loaded (see header file). fetchMore(-1) will fetch all available hunks.

DiffView:
The verticalScrollBar determines if more hunks are loaded (FileWidget) or more files are loaded. fetchMore(-1) will fetch 4 more files.

When fetching a huge added file (which only has 1 hunk) the app still freezes while loading the editor. You can see a spiking cpu utilization but if the file is loaded everything is back on track. I have no file with a hung amount of hunks, please do a performance test for that case.

(This is almost the same behavior as the CommitList scrollbar and that is what I wanted to achieve)

### CODE REVIEW

**Comment by Murmele** [comment]
Loading hunks dynamically will not work properly like this. Showing is fine, but single line staging will not work. See my code comments from the other merge request

**Comment by stefanknotzer** [comment]
I know this is not the last patch on this branch, I wanted you to approve the loading of hunks and files.
For now I would be happy if the loading and showing part is working.

**Comment by Murmele** [comment]
I will check it out

**Comment by stefanknotzer** [comment]
Testing would be very appreciated!
I already found some minor issues (context line calculation) and will have a closer look at partially staging next year.

**Comment by stefanknotzer** [comment]
The last part is the hardest: the HunkWidget...
I think I need a few days to get through all the HunkWidget functions in order to find a good/clean/working solution

**Comment by stefanknotzer** [comment]
My "review" is done. I did a ton of testing and debugging to get that working.
Future options:
- Test, review and merge into master
- Cleanup every single DiffView source before merge
- Do the cleanup and optimizations on a new branch after merge

**Pull request merged**
