### PR TITLE
New setting to hide avatars

### PR DESCRIPTION
**Pull request by codeschrat**
This addresses #332 

The new setting would read "show avatars" and would be false by default. This changes the current behavior: currently avatars are shown and there is no way to hide them. But I suggest positively formulated options/settings and an opt-in rather than an opt-out.

The last commit of this PR outlines an approach to get rid of magic strings for settings keys.
The current implementation is error-prone for multiple reasons: typos will result in different keys; there is no way to prevent using the same key twice. Furthermore, using those keys as magic strings exposes details of the current implementation, which would make it hard to change it.
Those issues are addressed in the last commit. If you don't like it, I could drop it; if you like it, it either may be just an extension to the current interface of the settings system or the interface of the settings system could be revised in a separate task.

### CODE REVIEW

**Review by exactly-one-kas — APPROVED** [review]

**Comment by exactly-one-kas** [comment]
Looks good, thanks!

@Murmele I think putting the settings into a centralized enum is a good idea, what do you think?

**Comment by Murmele** [comment]
Thank you for the patch! Yes this is a really good idea!
- Is there anything against using `enum class`?
- For promts already enums are used -> switch to enum class?
- Settings::setValue(QString, ...) -> private (internal)
- Settings::value(QString, ...) -> private (internal)
Shall we use SettingsId also for Prompts?

SettingsId as template with enum class as parameter and initialize a virtual function which has to be reimplemented in derived classes?

**Comment by codeschrat** [comment]
Thanks for your positive feedback.

There's nothing against scoped enums; I changed that and this revealed one forgotten cast in the unit test.

Regarding the idea of a template class: I implemented this using CRTP and applied it to `Prompt` as well. As I'm not sure whether this corresponds to your idea, consider this as a sketch! (E.g., this would need some better naming to not name `Prompt` three times in one single identifier.) I'm curious about other suggestions.
Another question would be, whether to group other settings as well -- now it's `Prompt` vs. all the others; I would not enforce such grouping if it has no advantages.

Regarding `Settings:setValue(QString, )` and `Settings::value(QString[,])`: They need to be public as long as some settings use magic strings. I suggest to wipe those out in a separate task -- either before this PR (i.e., as a prerequisite) or afterwards (i.e., as clean-up), that's up to you.

**Comment by Murmele** [comment]
hi @codeschrat.

Thanks for the work! Looks pretty nice now. We can do the cleanup afterwards.

**Review by Murmele — APPROVED** [review]

**Comment by Murmele** [comment]
@codeschrat  can you format the code (execute cl-fmt.sh locally)? There are some compile issues

**Comment by codeschrat** [comment]
Formatted the code.
Sorry for the inconvenience; my IDE will take care for this in the future.

**Comment by Murmele** [comment]
> 

Don't worry. It happens also for me. The CI is there to tell it to us ^^

**Comment by codeschrat** [comment]
Argh, I trusted a clang warning solely w/o re-building, so I removed an include in a header file and forgot that it might be used in the respective cpp file…  I fixed this now.

**Comment by codeschrat** [comment]
One test couldn't be built; this is fixed now.
Is there an **easy** way to build and run **all** tests locally? (I'm using _QtCreator_, and it doesn't show them in the _Tests_ view.)

**Comment by Murmele** [comment]
> One test couldn't be built; this is fixed now. Is there an **easy** way to build and run **all** tests locally? (I'm using _QtCreator_, and it doesn't show them in the _Tests_ view.)

If you go into the build folder, and run there ninja check

**Pull request merged**
