### PR TITLE
Add sort by column.  Force all columns headers to be initialized.

### PR DESCRIPTION
**Pull request by gh-devnull**

### CODE REVIEW

**Comment by Murmele** [comment]
The tests are failing

**Comment by gh-devnull** [comment]
Hm.  Looks like they are coming from commits that aren't mine - might be a bad merge.  

OK, ignore this for now while I see how to get a branch with just my commit.  

#632 builds OK and has successful tests (if you exclude the complaint about QT not installing on Windows - I have no idea what that's about).  Since this one builds on that, maybe it makes sense to focus on that first.

**Comment by Murmele** [comment]
On Linux:


The following tests FAILED:
	 17 - TreeView (Failed)
	 23 - fileContextMenu (Failed)

**Comment by Murmele** [comment]
@gh-devnull Can you clean this up?

**Comment by Murmele** [comment]
Is this still needed when merging #664 ?

**Comment by gh-devnull** [comment]
Agreed.  #664 includes this functionality.  I've closed this as a result.

**Pull request closed without merging**
