### PR TITLE
Add support for excluded patterns getting listed by `git lfs track`

### LINKED ISSUE #119: [Bug] Git-LFS backend incorrectly parsing tracked items
`git-lfs track` returns output such as (Unreal Engine example):

```
Listing tracked patterns
    Content/** (.gitattributes)
    *.uasset (.gitattributes)
    *.umap (.gitattributes)
Listing excluded patterns
```

Because of the logic in `QStringList Repository::lfsTracked()` in `src/git/Repository.cpp`, Gittyup currently appends an extra (incorrect) line to the list of tracked items, called “Listing”.

### PR DESCRIPTION
**Pull request by exactly-one-kas**
Fixes #119

### CODE REVIEW

**Comment by OdinVex** [comment]
See https://github.com/Murmele/Gittyup/issues/119 for input on the issue and this particular patch.

**Comment by Murmele** [comment]
Adding also to the excluded patterns a footer?

**Comment by OdinVex** [comment]
@Murmele, `git-lfs track` isn't apparently designed (or assumed safe, either) for machine-parsing. The next milestone of `git-lfs` will hopefully have a machine-safe output for tracking. For now, it cannot be relied upon to simply use strings to delimit the output in the way @exactly-one-kas has chosen because `git-lfs` is localizable away from English. I have determined it reasonably safe based on several languages to use `line[0] != ' '` as I did. It may be best to use version-detection for `git-lfs` to provide forward-compatibility to handle current older versions of `git-lfs`.

**Comment by exactly-one-kas** [comment]
I'll add a label for the upper list and use @OdinVex's change for output parsing

**Comment by Murmele** [comment]
> @Murmele, `git-lfs track` isn't apparently designed (or assumed safe, either) for machine-parsing. The next milestone of `git-lfs` will hopefully have a machine-safe output for tracking. **For now, it cannot be relied upon to simply use strings to delimit the output in the way @exactly-one-kas has chosen because `git-lfs` is localizable away from English.** I have determined it reasonably safe based on several languages to use `line[0] != ' '` as I did. It may be best to use version-detection for `git-lfs` to provide forward-compatibility to handle current older versions of `git-lfs`.

Do you think as workaround parsing the .gitattributes file is an option?

**Comment by OdinVex** [comment]
@Murmele, You'd be reinventing a more complex wheel. I think the only two options are:

- Temporarily remove editing/viewing of attributes until `git-lfs` reaches the hopeful `3.2.0` milestone release which should contain a machine-usable output.
- Parse it assuming the following: The first line can be skipped and all subsequent lines can be counted until `line[0] != ' '` becomes true, at which point you could assume the rest are then the excluded list entries. This should be safe, but is...hackish and tacky?

**Comment by exactly-one-kas** [comment]
> Adding also to the excluded patterns a footer?

As far as I see, the exclusion patterns can't be edited via the Git LFS CLI, and I agree with @OdinVex that manually implementing `.gitattribute` handling is too much for this

**Comment by exactly-one-kas** [comment]
> I'd very much like to see the entire line of each entry, as some have custom attributes, such as whether to see them as binary or text, et cetera.

I can try tackling this after #107 is done. Please create a new issue for this, since that is out of scope for #119

**Review by Murmele — APPROVED** [review]

**Comment by OdinVex** [comment]
> > I'd very much like to see the entire line of each entry, as some have custom attributes, such as whether to see them as binary or text, et cetera.
> 
> I can try tackling this after #107 is done. Please create a new issue for this, since that is out of scope for #119

Not sure that it's too far out of scope to need a second Issue, it's just using removing `.section(' ', 0, 0)` from the lines adding to tracked/excluded. It just seems a bit pedantic (or maybe I'm too lax on rules of 'Issue per change/suggestion').

**Comment by OdinVex** [comment]
I think you meant to use `QString::SkipEmptyParts`, not `Qt::SkipEmptyParts`. Broken patch.

**Comment by exactly-one-kas** [comment]
> it's just using removing .section(' ', 0, 0) from the lines adding to tracked/excluded

Fair point, I haven't looked into that at that point, but the PR is merged now :/
Then again, that would change already implemented behavior, so I'm not sure about this.

@Murmele what's your opinion on this?

**Comment by OdinVex** [comment]
@exactly-one-kas, I don't think it really changes anything except what is shown in the text-box, it just adds details to the entries already there. But yes, agreed @Murmele should be asked, their project. :)

**Comment by Murmele** [comment]
@exactly-one-kas sorry did not know. Perhaps I never used lfs yet so you can decide how you would like to have it. 

@OdinVex no it is not my project its the product of every contributor 😄.

**Comment by OdinVex** [comment]
> @exactly-one-kas sorry did not know. Perhaps I never used lfs yet so you can decide how you would like to have it.

LFS entries can most definitely have unique parameters. Only showing which entries without their parameters just forces me to ignore the LFS in Gittyup entirely to review the file instead. It defeats the purpose in my situation at least.

> @OdinVex no it is not my project its the product of every contributor smile.

Thank you, but someone should oversee things, is what I meant. An ultimate deciding lead on which direction. You wouldn't want someone to start replacing all the code with malicious content, for example.

**Comment by Murmele** [comment]
Should we create an issue to track this instead of discussing in a merged pr?
I have to checkout next days lfs to get a better understanding

**Comment by OdinVex** [comment]
> Should we create an issue to track this instead of discussing in a merged pr? I have to checkout next days lfs to get a better understanding

To track what? Your decision. :)

**Pull request merged**
