### PR TITLE
Mac os fix

### PR DESCRIPTION
**Pull request by Murmele**
Update scintilla version which fixes a bug in XCode 12: https://sourceforge.net/p/scintilla/bugs/2187/

Disable Touchbar because it leads to a division by zero.

- [x] Windows build running
- [x] Flatpak build running
- [x] Linux debugging

### CODE REVIEW

**Comment by Murmele** [comment]
Crashes on linux

**Comment by Murmele** [comment]
I had to abort the mac build because the tests are in an infinity loop. Build worked fine. Flatpak looks good, Linux debug worked also fine

**Comment by Murmele** [comment]
Fixes #35

**Comment by Murmele** [comment]
@jonathanjsimon can you try the mac build in the artifacts section of the following build: https://github.com/Murmele/Gittyup/actions/runs/2228867509

**Comment by jonathanjsimon** [comment]
@Murmele I was able to download it but my Mac is running 10.15.7, which is below the minimum. My colleague was able to run it on his machine running 12.x. I guess I'll have to bite the bullet and update my OS.

**Comment by Murmele** [comment]
Yes if possible to update this would be nice. Currently we don't have any active macOs developer so I don't know why at least a specific version is needed so we let it where it is

**Comment by jonathanjsimon** [comment]
I'll have to find a good time for my system to be down for an hour or so and that there aren't any other softwares depending on the version of macOS I have. I'll get back to you ASAP.

**Comment by Murmele** [comment]
@exactly-one-kas can you try if it is still working on windows? I had to update scintilla to get it run

**Pull request merged**
