### PR TITLE
Adds the checkbox SVGs

### PR DESCRIPTION
**Pull request by mmahmoudian**
These are something I drew in Inkscape.

### CODE REVIEW

**Comment by mmahmoudian** [comment]
Don't merge this

**Comment by Murmele** [comment]
why not merging? Please then mark as draft.

**Comment by Murmele** [comment]
@mmahmoudian can you test?

**Comment by Murmele** [comment]
@mmahmoudian  can you have a look on  #86. If it is fine for you, please close this MR

**Pull request closed without merging**
