### PR TITLE
Fix crash when having errors while adding a remote account

### PR DESCRIPTION
**Pull request by exactly-one-kas**
Also improve error messages for remote account connection failures

This fixes an access to a dangling pointer when remote account authentication fails

### CODE REVIEW

**Review by Murmele — APPROVED** [review]

**Comment by Murmele** [comment]
I will test the flatpak package then I will merge

**Comment by Murmele** [comment]
Should we create a new version after this mr or isn't it that important?

**Comment by exactly-one-kas** [comment]
It would fix #98

Since this happens only when adding an account, and probably has for quite some time (and we're not getting too many reports), I'd say this isn't urgent, but we should aim to put out a release soonish

**Comment by Murmele** [comment]
Sorry I will check it out today in the afternoon

**Review by Murmele — APPROVED** [review]

**Comment by Murmele** [comment]
@exactly-one-kas can you fix the conflict than you can merge it

**Pull request merged**
