### PR TITLE
Improve windows app icon

### PR DESCRIPTION
**Pull request by exactly-one-kas**

### CODE REVIEW

**Comment by Murmele** [comment]
Does it look on windows also the same?
grafik

When I open the old and the new one in Gimp, it looks fine maybe there is still a bug in it?

**Review by Murmele — APPROVED** [review]

**Comment by exactly-one-kas** [comment]
I think that may be a bug with QT's rendering on linux?
image

**Comment by Murmele** [comment]
> I think that may be a bug with QT's rendering on linux? image

But my image was on windows. Your one is also on windows or?

**Comment by exactly-one-kas** [comment]
Yes it is. I created #157 to address the issue. Looks (somewhat) fine on Linux
grafik

**Comment by Murmele** [comment]
thanks :)

**Pull request merged**
